//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Jogos Criados\TCC\Code_In_Hand\Assets\Grammar\CardCode.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class CardCodeLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, INTEGER=24, 
		FLOAT=25, STRING=26, BOOL=27, NULL=28, WS=29, IDENTIFIER=30;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "T__11", "T__12", "T__13", "T__14", "T__15", "T__16", 
		"T__17", "T__18", "T__19", "T__20", "T__21", "T__22", "INTEGER", "FLOAT", 
		"STRING", "BOOL", "NULL", "WS", "IDENTIFIER"
	};


	public CardCodeLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public CardCodeLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "';'", "'IF'", "'ELSE'", "'PRINT'", "'('", "')'", "'!'", "'*'", 
		"'/'", "'%'", "'+'", "'-'", "'=='", "'!='", "'>'", "'<'", "'>='", "'<='", 
		"'and'", "'or'", "'{'", "'}'", "'='", null, null, null, null, "'null'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		"INTEGER", "FLOAT", "STRING", "BOOL", "NULL", "WS", "IDENTIFIER"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "CardCode.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static CardCodeLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', ' ', '\xB8', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', 
		'\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', 
		'\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', 
		'\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', 
		'\x3', '\x17', '\x3', '\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', 
		'\x6', '\x19', '~', '\n', '\x19', '\r', '\x19', '\xE', '\x19', '\x7F', 
		'\x3', '\x1A', '\x6', '\x1A', '\x83', '\n', '\x1A', '\r', '\x1A', '\xE', 
		'\x1A', '\x84', '\x3', '\x1A', '\x3', '\x1A', '\x6', '\x1A', '\x89', '\n', 
		'\x1A', '\r', '\x1A', '\xE', '\x1A', '\x8A', '\x3', '\x1B', '\x3', '\x1B', 
		'\a', '\x1B', '\x8F', '\n', '\x1B', '\f', '\x1B', '\xE', '\x1B', '\x92', 
		'\v', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\a', '\x1B', 
		'\x97', '\n', '\x1B', '\f', '\x1B', '\xE', '\x1B', '\x9A', '\v', '\x1B', 
		'\x3', '\x1B', '\x5', '\x1B', '\x9D', '\n', '\x1B', '\x3', '\x1C', '\x3', 
		'\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', 
		'\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x5', '\x1C', '\xA8', '\n', '\x1C', 
		'\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', 
		'\x3', '\x1E', '\x6', '\x1E', '\xB0', '\n', '\x1E', '\r', '\x1E', '\xE', 
		'\x1E', '\xB1', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1F', '\x3', '\x1F', 
		'\x3', '\x1F', '\x2', '\x2', ' ', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', 
		'\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', 
		'\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', 
		'\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', '%', '\x14', '\'', '\x15', 
		')', '\x16', '+', '\x17', '-', '\x18', '/', '\x19', '\x31', '\x1A', '\x33', 
		'\x1B', '\x35', '\x1C', '\x37', '\x1D', '\x39', '\x1E', ';', '\x1F', '=', 
		' ', '\x3', '\x2', '\b', '\x3', '\x2', '\x32', ';', '\x3', '\x2', '$', 
		'$', '\x3', '\x2', ')', ')', '\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', 
		'\"', '\x5', '\x2', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x6', 
		'\x2', '\x32', ';', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x2', 
		'\xBF', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', 
		')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', '\x2', '\x33', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x35', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x37', '\x3', '\x2', '\x2', '\x2', '\x2', '\x39', '\x3', '\x2', '\x2', 
		'\x2', '\x2', ';', '\x3', '\x2', '\x2', '\x2', '\x2', '=', '\x3', '\x2', 
		'\x2', '\x2', '\x3', '?', '\x3', '\x2', '\x2', '\x2', '\x5', '\x41', '\x3', 
		'\x2', '\x2', '\x2', '\a', '\x44', '\x3', '\x2', '\x2', '\x2', '\t', 'I', 
		'\x3', '\x2', '\x2', '\x2', '\v', 'O', '\x3', '\x2', '\x2', '\x2', '\r', 
		'Q', '\x3', '\x2', '\x2', '\x2', '\xF', 'S', '\x3', '\x2', '\x2', '\x2', 
		'\x11', 'U', '\x3', '\x2', '\x2', '\x2', '\x13', 'W', '\x3', '\x2', '\x2', 
		'\x2', '\x15', 'Y', '\x3', '\x2', '\x2', '\x2', '\x17', '[', '\x3', '\x2', 
		'\x2', '\x2', '\x19', ']', '\x3', '\x2', '\x2', '\x2', '\x1B', '_', '\x3', 
		'\x2', '\x2', '\x2', '\x1D', '\x62', '\x3', '\x2', '\x2', '\x2', '\x1F', 
		'\x65', '\x3', '\x2', '\x2', '\x2', '!', 'g', '\x3', '\x2', '\x2', '\x2', 
		'#', 'i', '\x3', '\x2', '\x2', '\x2', '%', 'l', '\x3', '\x2', '\x2', '\x2', 
		'\'', 'o', '\x3', '\x2', '\x2', '\x2', ')', 's', '\x3', '\x2', '\x2', 
		'\x2', '+', 'v', '\x3', '\x2', '\x2', '\x2', '-', 'x', '\x3', '\x2', '\x2', 
		'\x2', '/', 'z', '\x3', '\x2', '\x2', '\x2', '\x31', '}', '\x3', '\x2', 
		'\x2', '\x2', '\x33', '\x82', '\x3', '\x2', '\x2', '\x2', '\x35', '\x9C', 
		'\x3', '\x2', '\x2', '\x2', '\x37', '\xA7', '\x3', '\x2', '\x2', '\x2', 
		'\x39', '\xA9', '\x3', '\x2', '\x2', '\x2', ';', '\xAF', '\x3', '\x2', 
		'\x2', '\x2', '=', '\xB5', '\x3', '\x2', '\x2', '\x2', '?', '@', '\a', 
		'=', '\x2', '\x2', '@', '\x4', '\x3', '\x2', '\x2', '\x2', '\x41', '\x42', 
		'\a', 'K', '\x2', '\x2', '\x42', '\x43', '\a', 'H', '\x2', '\x2', '\x43', 
		'\x6', '\x3', '\x2', '\x2', '\x2', '\x44', '\x45', '\a', 'G', '\x2', '\x2', 
		'\x45', '\x46', '\a', 'N', '\x2', '\x2', '\x46', 'G', '\a', 'U', '\x2', 
		'\x2', 'G', 'H', '\a', 'G', '\x2', '\x2', 'H', '\b', '\x3', '\x2', '\x2', 
		'\x2', 'I', 'J', '\a', 'R', '\x2', '\x2', 'J', 'K', '\a', 'T', '\x2', 
		'\x2', 'K', 'L', '\a', 'K', '\x2', '\x2', 'L', 'M', '\a', 'P', '\x2', 
		'\x2', 'M', 'N', '\a', 'V', '\x2', '\x2', 'N', '\n', '\x3', '\x2', '\x2', 
		'\x2', 'O', 'P', '\a', '*', '\x2', '\x2', 'P', '\f', '\x3', '\x2', '\x2', 
		'\x2', 'Q', 'R', '\a', '+', '\x2', '\x2', 'R', '\xE', '\x3', '\x2', '\x2', 
		'\x2', 'S', 'T', '\a', '#', '\x2', '\x2', 'T', '\x10', '\x3', '\x2', '\x2', 
		'\x2', 'U', 'V', '\a', ',', '\x2', '\x2', 'V', '\x12', '\x3', '\x2', '\x2', 
		'\x2', 'W', 'X', '\a', '\x31', '\x2', '\x2', 'X', '\x14', '\x3', '\x2', 
		'\x2', '\x2', 'Y', 'Z', '\a', '\'', '\x2', '\x2', 'Z', '\x16', '\x3', 
		'\x2', '\x2', '\x2', '[', '\\', '\a', '-', '\x2', '\x2', '\\', '\x18', 
		'\x3', '\x2', '\x2', '\x2', ']', '^', '\a', '/', '\x2', '\x2', '^', '\x1A', 
		'\x3', '\x2', '\x2', '\x2', '_', '`', '\a', '?', '\x2', '\x2', '`', '\x61', 
		'\a', '?', '\x2', '\x2', '\x61', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x62', 
		'\x63', '\a', '#', '\x2', '\x2', '\x63', '\x64', '\a', '?', '\x2', '\x2', 
		'\x64', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x65', '\x66', '\a', '@', 
		'\x2', '\x2', '\x66', ' ', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\a', 
		'>', '\x2', '\x2', 'h', '\"', '\x3', '\x2', '\x2', '\x2', 'i', 'j', '\a', 
		'@', '\x2', '\x2', 'j', 'k', '\a', '?', '\x2', '\x2', 'k', '$', '\x3', 
		'\x2', '\x2', '\x2', 'l', 'm', '\a', '>', '\x2', '\x2', 'm', 'n', '\a', 
		'?', '\x2', '\x2', 'n', '&', '\x3', '\x2', '\x2', '\x2', 'o', 'p', '\a', 
		'\x63', '\x2', '\x2', 'p', 'q', '\a', 'p', '\x2', '\x2', 'q', 'r', '\a', 
		'\x66', '\x2', '\x2', 'r', '(', '\x3', '\x2', '\x2', '\x2', 's', 't', 
		'\a', 'q', '\x2', '\x2', 't', 'u', '\a', 't', '\x2', '\x2', 'u', '*', 
		'\x3', '\x2', '\x2', '\x2', 'v', 'w', '\a', '}', '\x2', '\x2', 'w', ',', 
		'\x3', '\x2', '\x2', '\x2', 'x', 'y', '\a', '\x7F', '\x2', '\x2', 'y', 
		'.', '\x3', '\x2', '\x2', '\x2', 'z', '{', '\a', '?', '\x2', '\x2', '{', 
		'\x30', '\x3', '\x2', '\x2', '\x2', '|', '~', '\t', '\x2', '\x2', '\x2', 
		'}', '|', '\x3', '\x2', '\x2', '\x2', '~', '\x7F', '\x3', '\x2', '\x2', 
		'\x2', '\x7F', '}', '\x3', '\x2', '\x2', '\x2', '\x7F', '\x80', '\x3', 
		'\x2', '\x2', '\x2', '\x80', '\x32', '\x3', '\x2', '\x2', '\x2', '\x81', 
		'\x83', '\t', '\x2', '\x2', '\x2', '\x82', '\x81', '\x3', '\x2', '\x2', 
		'\x2', '\x83', '\x84', '\x3', '\x2', '\x2', '\x2', '\x84', '\x82', '\x3', 
		'\x2', '\x2', '\x2', '\x84', '\x85', '\x3', '\x2', '\x2', '\x2', '\x85', 
		'\x86', '\x3', '\x2', '\x2', '\x2', '\x86', '\x88', '\a', '\x30', '\x2', 
		'\x2', '\x87', '\x89', '\t', '\x2', '\x2', '\x2', '\x88', '\x87', '\x3', 
		'\x2', '\x2', '\x2', '\x89', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x8A', 
		'\x88', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8B', '\x3', '\x2', '\x2', 
		'\x2', '\x8B', '\x34', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x90', '\a', 
		'$', '\x2', '\x2', '\x8D', '\x8F', '\n', '\x3', '\x2', '\x2', '\x8E', 
		'\x8D', '\x3', '\x2', '\x2', '\x2', '\x8F', '\x92', '\x3', '\x2', '\x2', 
		'\x2', '\x90', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x90', '\x91', '\x3', 
		'\x2', '\x2', '\x2', '\x91', '\x93', '\x3', '\x2', '\x2', '\x2', '\x92', 
		'\x90', '\x3', '\x2', '\x2', '\x2', '\x93', '\x9D', '\a', '$', '\x2', 
		'\x2', '\x94', '\x98', '\a', ')', '\x2', '\x2', '\x95', '\x97', '\n', 
		'\x4', '\x2', '\x2', '\x96', '\x95', '\x3', '\x2', '\x2', '\x2', '\x97', 
		'\x9A', '\x3', '\x2', '\x2', '\x2', '\x98', '\x96', '\x3', '\x2', '\x2', 
		'\x2', '\x98', '\x99', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9B', '\x3', 
		'\x2', '\x2', '\x2', '\x9A', '\x98', '\x3', '\x2', '\x2', '\x2', '\x9B', 
		'\x9D', '\a', ')', '\x2', '\x2', '\x9C', '\x8C', '\x3', '\x2', '\x2', 
		'\x2', '\x9C', '\x94', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x36', '\x3', 
		'\x2', '\x2', '\x2', '\x9E', '\x9F', '\a', 'v', '\x2', '\x2', '\x9F', 
		'\xA0', '\a', 't', '\x2', '\x2', '\xA0', '\xA1', '\a', 'w', '\x2', '\x2', 
		'\xA1', '\xA8', '\a', 'g', '\x2', '\x2', '\xA2', '\xA3', '\a', 'h', '\x2', 
		'\x2', '\xA3', '\xA4', '\a', '\x63', '\x2', '\x2', '\xA4', '\xA5', '\a', 
		'n', '\x2', '\x2', '\xA5', '\xA6', '\a', 'u', '\x2', '\x2', '\xA6', '\xA8', 
		'\a', 'g', '\x2', '\x2', '\xA7', '\x9E', '\x3', '\x2', '\x2', '\x2', '\xA7', 
		'\xA2', '\x3', '\x2', '\x2', '\x2', '\xA8', '\x38', '\x3', '\x2', '\x2', 
		'\x2', '\xA9', '\xAA', '\a', 'p', '\x2', '\x2', '\xAA', '\xAB', '\a', 
		'w', '\x2', '\x2', '\xAB', '\xAC', '\a', 'n', '\x2', '\x2', '\xAC', '\xAD', 
		'\a', 'n', '\x2', '\x2', '\xAD', ':', '\x3', '\x2', '\x2', '\x2', '\xAE', 
		'\xB0', '\t', '\x5', '\x2', '\x2', '\xAF', '\xAE', '\x3', '\x2', '\x2', 
		'\x2', '\xB0', '\xB1', '\x3', '\x2', '\x2', '\x2', '\xB1', '\xAF', '\x3', 
		'\x2', '\x2', '\x2', '\xB1', '\xB2', '\x3', '\x2', '\x2', '\x2', '\xB2', 
		'\xB3', '\x3', '\x2', '\x2', '\x2', '\xB3', '\xB4', '\b', '\x1E', '\x2', 
		'\x2', '\xB4', '<', '\x3', '\x2', '\x2', '\x2', '\xB5', '\xB6', '\t', 
		'\x6', '\x2', '\x2', '\xB6', '\xB7', '\t', '\a', '\x2', '\x2', '\xB7', 
		'>', '\x3', '\x2', '\x2', '\x2', '\v', '\x2', '\x7F', '\x84', '\x8A', 
		'\x90', '\x98', '\x9C', '\xA7', '\xB1', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
